### ISSUE TITLE
TypeError: Cannot read property 'workers' of undefined

### ISSUE THREAD

**Issue by pirmax** [BruceHem/nuxtjs-extensions#2]
Hi,

I've this error when I compile code:

> TypeError: Cannot read property 'workers' of undefined
>     at Builder.<anonymous> (/home/maxence/projects/test14/node_modules/nuxtjs-extensions/src/modules/typescript.ts:17:69)
>     at Builder.<anonymous> (/home/maxence/projects/test14/node_modules/nuxt/lib/common/utils.js:112:17)
>     at Builder.webpackClientConfig (/home/maxence/projects/test14/node_modules/nuxt/lib/builder/webpack/client.config.js:219:54)
>     at Builder.webpackBuild (/home/maxence/projects/test14/node_modules/nuxt/lib/builder/builder.js:487:46)
>     at Builder.build (/home/maxence/projects/test14/node_modules/nuxt/lib/builder/builder.js:168:16)
>     at <anonymous>

Could you help me please?

**Comment by chanlito** [comment]
Can you show me your `nuxt.config.js`?

**Comment by pirmax** [comment]
It's nuxt.config.js of your repo: https://github.com/chanlito/nuxt-ts-starter/blob/master/nuxt.config.js

I've only update all packages...

Thanks.

**Comment by chanlito** [comment]
@pirmax please try with this https://github.com/chanlito/nuxt-ts-module

**Comment by pirmax** [comment]
Is it possible to update all your repository ? It interests me to start a project. Thank very much !
